### PR TITLE
Add recipe for plotting radar on terrain background

### PR DESCRIPTION
**Pull request by youstormorg**
For plotting radar reflectivity from AUS2200 data on a black and white terrain background. My first test upload.

### CODE REVIEW

**Review by navidcy — CHANGES_REQUESTED** [review]
@youstormorg this is great!

It'd be nice if you add a title to the notebook and elaborate a bit on the first sentence explaining what this notebook does.

See https://atmospheric-cookbook.readthedocs.io/en/latest/guidelines.html for how the first cell should be. You should add a title with Markdown like:

```
# Title of the example

This recipe does this and the other....
```

**Comment by navidcy** [comment]
Also could you edit the pull request title to describe what this pull request add? E.g. "Add recipe for doing this and that"?

**Comment by youstormorg** [comment]
Thanks for the tips! I'll update this script and future ones following the guidelines.

**Review by navidcy — APPROVED** [review]
Just a few more comments. These packages seem to be imported but not use:

```python
import pandas as pd
import xesmf as xe
import netCDF4 as nc4
```

So it'd be nice if we don't import them so that we don't confuse people.

But there is also much more space for improvement and we don't need to do everything now. 

This is a great start! Thanks!

**Comment by navidcy** [comment]
feel free to merge or remove the unused packages and the merge, either way!

**Comment by youstormorg** [comment]
> Just a few more comments. These packages seem to be imported but not use:
> 
> ```python
> import pandas as pd
> import xesmf as xe
> import netCDF4 as nc4
> ```
> 
> So it'd be nice if we don't import them so that we don't confuse people.
> 
> But there is also much more space for improvement and we don't need to do everything now.
> 
> This is a great start! Thanks!

Yes I'm not surprised about this and will remove these lines. I have been doing mass imports of things because I only began learning python properly this year. Thanks for pointing this out!

**Comment by navidcy** [comment]
Nice -- thanks!

**Comment by navidcy** [comment]
Welcome to the repo's contributors @youstormorg!! 🎉🎉🎉

**Pull request merged**
